import asyncio
from pathlib import Path

from agents import Agent, Runner, trace
from agents.mcp import MCPServerStdio
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SANDBOX_DIR = PROJECT_ROOT / "sandbox"
NOTES_FILE = SANDBOX_DIR / "agentic-ai-notes.md"
MERMAID_FILE = SANDBOX_DIR / "agentic-ai.mmd"
PNG_FILE = SANDBOX_DIR / "agentic-ai.png"
load_dotenv(override=True)

search_params = {
    "command": "uvx",
    "args": ["duckduckgo-mcp-server"],
}

files_params = {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-filesystem", str(SANDBOX_DIR)],
}

mermaid_params = {
    "command": "uvx",
    "args": ["--from", "mcp-mermaid-image-gen", "mcp_mermaid_image_gen"],
}

instructions = f"""
You have exactly three MCP tool sets: DuckDuckGo search, filesystem, and Mermaid diagram generation.
Use only these tools. Do not assume any other capabilities.

Step 1 — Research (DuckDuckGo)
- Use search to find how Agentic AI works.
- Use fetch_content on the best results to read full pages from the web.
- From that research, identify the workflow steps, components, and how they connect.
- Do not use a predefined workflow — derive it from what you find online.

Step 2 — Notes (filesystem)
- Save research to: {NOTES_FILE}
- Include the workflow steps and relationships you discovered.

Step 3 — Flow diagram (Mermaid only)
- Write the Mermaid source you derived from research to: {MERMAID_FILE}
- Use a flowchart (flowchart LR or flowchart TD) with one node per step and arrows between them.
- Call generate_mermaid_diagram_file with:
  - code: the same Mermaid source
  - folder: {SANDBOX_DIR}
  - name: agentic-ai.png
  - format: png

Do not finish until {MERMAID_FILE} exists and {PNG_FILE} was generated by the Mermaid MCP tool.
"""

request = f"""
1. Search the web and read pages about how Agentic AI works.
2. Save your findings and discovered workflow to {NOTES_FILE}.
3. Build a flowchart from that research using Mermaid MCP tools:
   - save source to {MERMAID_FILE}
   - export PNG to {PNG_FILE}
Use only MCP tools from search, filesystem, and Mermaid.
"""


async def list_server_tools(name: str, server: MCPServerStdio) -> None:
    tools = await server.list_tools()
    print(f"\n{name} tools ({len(tools)}):")
    for tool in tools:
        print(f"  - {tool.name}")


async def main() -> None:
    SANDBOX_DIR.mkdir(parents=True, exist_ok=True)

    async with MCPServerStdio(
        params=files_params,
        client_session_timeout_seconds=120,
    ) as mcp_server_files:
        async with MCPServerStdio(
            params=search_params,
            client_session_timeout_seconds=30,
        ) as mcp_server_search:
            async with MCPServerStdio(
                params=mermaid_params,
                client_session_timeout_seconds=120,
            ) as mcp_server_mermaid:
                await list_server_tools("Filesystem", mcp_server_files)
                await list_server_tools("DuckDuckGo", mcp_server_search)
                await list_server_tools("Mermaid", mcp_server_mermaid)

                agent = Agent(
                    name="agentic_ai_diagrammer",
                    instructions=instructions,
                    model="gpt-4.1-mini",
                    mcp_servers=[
                        mcp_server_files,
                        mcp_server_search,
                        mcp_server_mermaid,
                    ],
                )

                with trace("agentic_ai_diagrammer"):
                    result = await Runner.run(agent, request, max_turns=50)

                print("\nFinal output:")
                print(result.final_output)


if __name__ == "__main__":
    asyncio.run(main())
